services:
  # PHP-FPM
  php-httpd-socket:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    container_name: php-httpd-socket
    restart: unless-stopped
    volumes:
      - unix-socket:/var/run/php
      - ./public:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini:ro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - php-httpd-socket-network
    healthcheck:
      test: [ "CMD", "cgi-fcgi", "-bind", "-connect", "/var/run/php/php-fpm.sock" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Веб-сервер Apache
  httpd-socket:
    image: httpd:2.4-alpine
    container_name: httpd-socket
    restart: unless-stopped
    ports:
      - "${HTTPD_PORT}:80"
    volumes:
      - unix-socket:/var/run/php
      - ./public:/var/www/html
      - ./docker/httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - php-httpd-socket-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost/" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      php-httpd-socket:
        condition: service_healthy

  # База данных MySQL
  mysql-httpd-socket:
    image: mysql:8.4
    container_name: mysql-httpd-socket
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - php-httpd-socket-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    # phpMyAdmin
  phpmyadmin-httpd-socket:
    image: phpmyadmin
    container_name: phpmyadmin-httpd-socket
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - php-httpd-socket-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost/" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      mysql-httpd-socket:
        condition: service_healthy

volumes:
  unix-socket:
  mysql-data:

networks:
  php-httpd-socket-network:
    driver: bridge
